### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by ehmatthes** [sayanbiswas-india/to-do-app-django#1]
Hello, @sayanbiswas-india. You asked for my help on reddit in deploying this project. Normally I wouldn't get involved, but I have been working on a simplified workflow for deploying to Heroku, and I was curious to see if it works on your project. It does! I'll share the heroku-specific steps.

- Before you do this you need to be running your project in a virtual environment. I'm not sure you are, because I don't see a .gitignore file or a venv directory. We should see a .gitignore file, and your venv directory should not be committed.
- Then create a *requirements.txt* file using the command `pip freeze > requirements.txt`. Commit this change.
- Then follow the directions shown in the first section here: <https://github.com/ehmatthes/heroku-buildpack-python>
  - Where it says `git push heroku main`, you will probably use `git push heroku master`, because your main branch is called `master`.

**Comment by sayan-05** [comment]
Done
